import time

print('你好，我是 Python。欢迎你来和我做朋友🤗')
time.sleep(1)
print('很高兴认识你！让我来介绍一下自己吧~')
time.sleep(0.5)
print('有人说：我是迈入人工智能时代的第一道门槛。')
time.sleep(1)
print('也有人说：我是配合 excel 的自动化办公利器。')
time.sleep(1)
print('还有人说，我是编程初学者入门的最好选择。')
time.sleep(1)
print('但是，对你来说，我究竟应该是什么呢？')
time.sleep(1)
print('......')
time.sleep(0.5)
print('我只是你的工具：')
time.sleep(0.5)
print('你可以使用我替你去做重复、枯燥的工作！')
time.sleep(1)
print('你可以使用我帮你去计算、分析大规模的数据！')
time.sleep(1)
print('我会乖乖地听你的指令，完成你要做的事情；')
time.sleep(1)
print('我会解放你的双手，帮你提高工作效率；')
time.sleep(1)
print('我能助你成为职场高手，帮你升职加薪；')
time.sleep(1)
print('我是你的万能钥匙，打开新领域的大门！')
time.sleep(0.5)
print('(๑•̀ㅂ•́)و✧加油')